In [1]:
import numpy as np

In [3]:
x = np.array([0, 1, 0, 1], np.uint8)
y = np.array([0, 0, 1, 1], np.uint8)

print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.bitwise_not(x))

[0 0 0 1]
[0 1 1 1]
[0 1 1 0]
[255 254 255 254]


In [4]:
x = np.random.randint( low = 0, high = 9, size = 10 )
x

array([2, 4, 5, 5, 2, 4, 8, 7, 1, 3])

In [5]:
x = np.random.rand(3, 3)
x

array([[0.49057516, 0.14961487, 0.6973665 ],
       [0.22814399, 0.43431675, 0.6211095 ],
       [0.25335465, 0.61728774, 0.21234068]])

In [6]:
x = np.random.rand(100, 100)
x

array([[0.93240677, 0.61761159, 0.26479094, ..., 0.12273103, 0.36482046,
        0.73640916],
       [0.96100332, 0.75901093, 0.90206298, ..., 0.92841883, 0.59323272,
        0.27948827],
       [0.91910026, 0.22816148, 0.71076503, ..., 0.24223247, 0.66810472,
        0.57630375],
       ...,
       [0.47006924, 0.00742056, 0.87758324, ..., 0.77672237, 0.64833003,
        0.36744957],
       [0.19210458, 0.46801781, 0.64517326, ..., 0.77662456, 0.9566732 ,
        0.75818291],
       [0.63754803, 0.00337392, 0.37584052, ..., 0.5826088 , 0.61616659,
        0.61546871]])

In [7]:
x.shape

(100, 100)

In [8]:
x = np.random.rand(5, 5, 5)
x.shape

(5, 5, 5)

In [9]:
x

array([[[0.14761206, 0.3210426 , 0.9530574 , 0.50490507, 0.14041287],
        [0.64161894, 0.23258414, 0.10413331, 0.85171914, 0.12945882],
        [0.3861122 , 0.61259226, 0.1702914 , 0.15460448, 0.06794291],
        [0.62913523, 0.88175586, 0.05929762, 0.48821379, 0.02134197],
        [0.28009306, 0.96661295, 0.25518584, 0.84626432, 0.09020379]],

       [[0.92461414, 0.67820662, 0.26376146, 0.36943004, 0.37258462],
        [0.88912395, 0.57133179, 0.96182999, 0.32102698, 0.97686475],
        [0.46027824, 0.78410888, 0.85038369, 0.6197107 , 0.40664024],
        [0.02516661, 0.11668024, 0.92744596, 0.41097013, 0.07878203],
        [0.20206186, 0.76778445, 0.16195373, 0.90296524, 0.53408874]],

       [[0.17571356, 0.29379613, 0.80862533, 0.96145606, 0.6900998 ],
        [0.00198376, 0.07183378, 0.08882742, 0.58719604, 0.53353094],
        [0.69623007, 0.63220248, 0.04574714, 0.1092979 , 0.18120184],
        [0.36093292, 0.87199195, 0.30257104, 0.25464192, 0.2147597 ],
        [0.99947

In [10]:
x = np.random.randint( low = 0, high = 10, size = 10 )
x

array([5, 7, 3, 6, 6, 1, 9, 0, 2, 0])

In [11]:
np.median(x)

4.0

In [12]:
np.average(x)

3.9

In [13]:
np.mean(x)

3.9

In [ ]:
np.median(x)